Add initial build setup (#24)
* fix 'Failed to minify the code from this file' issue

* fix build 'error TS2300: Duplicate identifier 'Element'' issue

* fix missing gear icon from parent pr selector

* add initial extension build setup